### ISSUE TITLE
Install from config

### ISSUE THREAD

**Issue by lmachegger** [mys31f/bashsetup#1]
I really like the idea of that script!
It would be really cool though, if you could install the apps from a config file. 
Imagine a appconfig.json file, where you put all the apps you wanna install e.g.:
```
{
    "apps" = [ 
        "discord", 
        "lutris", 
        "steam"
    ]
}
```
The script could then take all the elements of the array in the config, and run `sudo pacman -S <appname>` for every element.

Just an idea that I thought that would be cool.

**Comment by mys31f** [comment]
That could be pretty cool, while also giving degrees of customizing as well. Though, this would only apply with some distros, because there are distros such as Ubuntu which requires many of the apps that I put in this script be installed from their .deb files.

**Comment by mys31f** [comment]
In addition, even in Arch based distros, there is a disparity between what apps are available between them. For example, yay is included in the Manjaro repos but is not there in Arch official repositories but only available in the AUR.
